[package]
name = "soroban-storage-contract"
version.workspace = true
edition.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "storage"
path = "./src/lib.rs"

[dependencies]
soroban-sdk = { workspace = true }
